// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/cristianapassos/18-DI/product"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire.go:

// resolve as dependencias no build
func NewUseCase(db *sql.DB) *product.ProductUseCase {
	productRepository := product.NewProductRepository(db)
	productUseCase := product.NewProdutUseCase(productRepository)
	return productUseCase
}
